version: "3"

networks:
  talakutnangan:
    external: false

services:
  web:
    build:
      context: .
      target: dev
    image: talakutnangan:dev
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.40"
    #       memory: 100M
    restart: on-failure
    networks:
      - talakutnangan
    volumes:
      - web_root:/var/www/html/app/web
      - type: bind
        source: "./web/pages"
        target: "/var/www/html/app/web/pages"
      - type: bind
        source: "./web/.nuxt"
        target: "/var/www/html/app/web/.nuxt"
    ports:
      - "16000:8000"
    command: npx nuxt dev --port 8000

  web_test:
    build:
      context: .
      target: test
    image: talakutnangan:test
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
    restart: on-failure
    volumes:
      - type: bind
        source: "./.git"
        target: "/var/www/html/.git"
      - type: bind
        source: "./web/pages"
        target: "/var/www/html/app/web/pages"
      - type: bind
        source: "./web/.nuxt"
        target: "/var/www/html/app/web/.nuxt"
      - web_root:/var/www/html/app/web
    tty: true
    stdin_open: false
    command: npx jest

  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=talakutnangan_test
    networks:
      - talakutnangan
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database:/var/lib/mysql

volumes:
  web_root:
