version: "3"

networks:
  talakutnangan:
    external: false

services:
  web:
    build:
      context: .
      target: dev
    image: talakutnangan:dev
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 100M
    restart: on-failure
    networks:
      - talakutnangan
    volumes:
      - "root:/var/www/html/app"
      - "./:/var/www/html/app/base"
    ports:
      - "16000:3000"
    depends_on:
      - database
    command: npm run dev

  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 450M
    networks:
      - talakutnangan
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database/server:/var/lib/mysql

volumes:
  root:
