version: "3"

networks:
  talakutnangan:
    external: false

services:
  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 450M
    networks:
      - talakutnangan
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database/server:/var/lib/mysql
