name: Web Back-end Unit Tests

on:
  push:
    paths:
      - 'shareable/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'server/**'
      - 'routes/**'
      - 't/helpers/**'
      - '.github/workflows/back-end.unit.yml'
      - 'jest.back.config.json'
      - 'jest.back.unit_ci.config.json'
      - 'jest.route.config.json'
      - 'jest.database.config.json'
  pull_request:
    types:
      - reopened
    branches:
      - master
    paths:
      - 'shareable/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'server/**'
      - 'routes/**'
      - 't/helpers/**'
      - '.github/workflows/back-end.unit.yml'
      - 'jest.back.config.json'
      - 'jest.back.unit_ci.config.json'
      - 'jest.route.config.json'
      - 'jest.database.config.json'

jobs:
  unit_tests_with_rarely_used_database:
    runs-on: ubuntu-latest
    steps:
    - name: Change to appropriate timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Singapore"
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Use .env.ci as the environment file for back-end
      run: mv .env.ci .env
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}_${{ hashFiles('jest.back.unit_ci.config.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}_${{ hashFiles('jest.back.unit_ci.config.json') }}
    - run: npm install
    - run: ./execute.ps1 -test unit_ci:back -compile
      shell: pwsh
      timeout-minutes: 5

  unit_route_tests_with_necessary_database:
    runs-on: ubuntu-latest
    steps:
    - name: Change to appropriate timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Singapore"
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}_${{ hashFiles('jest.route.config.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}_${{ hashFiles('jest.route.config.json') }}
    - run: npm install
    - run: ./execute.ps1 -test unit:route
      shell: pwsh
      timeout-minutes: 6

  unit_database_tests_with_necessary_database:
    runs-on: ubuntu-latest
    steps:
    - name: Change to appropriate timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Singapore"
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}_${{ hashFiles('jest.database.config.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}_${{ hashFiles('jest.database.config.json') }}
    - run: npm install
    - run: ./execute.ps1 -test unit:database
      shell: pwsh
      timeout-minutes: 5
