name: Web Back-end Unit Tests

on:
  push:
    paths:
      - 'shareable/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'server/**'
      - 'routes/**'
      - 't/helpers/**'
      - '.github/workflows/back-end.unit.yml'
      - 'jest.back.unit_ci.config.json'
  pull_request:
    types:
      - reopened
    branches:
      - master
    paths:
      - 'shareable/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'server/**'
      - 'routes/**'
      - 't/helpers/**'
      - '.github/workflows/back-end.unit.yml'
      - 'jest.back.unit_ci.config.json'

jobs:
  common_back-end_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}
          ${{ runner.os }}_
    - run: npm install
    - run: ./execute.ps1 -test unit:back -compile
      shell: pwsh
      timeout-minutes: 5

  database_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}
          ${{ runner.os }}_
    - run: npm install
    - run: ./execute.ps1 -test unit:database -compile
      shell: pwsh
      timeout-minutes: 5

  server_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}
          ${{ runner.os }}_
    - run: npm install
    - run: ./execute.ps1 -test unit:server -compile
      shell: pwsh
      timeout-minutes: 5

  route_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}
          ${{ runner.os }}_
    - run: npm install
    - run: ./execute.ps1 -test unit:routes -compile
      shell: pwsh
      timeout-minutes: 5
