name: Web Back-end Unit Tests

on:
  push:
    paths:
      - 'shareable/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'server/**'
      - 't/helpers/**'
      - '.github/workflows/back-end.unit.yml'
      - 'jest.back_ci.config.json'
  pull_request_target:
    types:
      - opened
      - reopened
      - review_requested
    branches:
      - master
    paths:
      - 'shareable/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'server/**'
      - 't/helpers/**'
      - '.github/workflows/back-end.unit.yml'
      - 'jest.back_ci.config.json'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}
          ${{ runner.os }}_
    - run: npm install
    - run: ./execute.ps1 -test unit:back_ci
      shell: pwsh
      timeout-minutes: 3
