name: Web Front-end Tests

on:
  push: []
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
    branches:
      - master
    paths:
      - 'pages/**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run test:unit
