name: Web Front-end Unit Tests

on:
  push:
    paths:
      - 'shareable/**'
      - 'common_front-end/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'components/**'
      - 'pages/**'
      - 't/helpers/**'
      - '.github/workflows/front-end.unit.yml'
      - 'jest.front.config.json'
      - 'jest.component.config.json'
      - 'jest.front.unit_ci.config.json'
  pull_request:
    types:
      - reopened
    branches:
      - master
    paths:
      - 'shareable/**'
      - 'common_front-end/**'
      - 'common_back-end/**'
      - 'database/**'
      - 'components/**'
      - 'pages/**'
      - 't/helpers/**'
      - '.github/workflows/front-end.unit.yml'
      - 'jest.front.config.json'
      - 'jest.component.config.json'
      - 'jest.front.unit_ci.config.json'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}
    - run: npm install
    - run: ./execute.ps1 -test unit_ci:front
      shell: pwsh
      timeout-minutes: 3
