name: Shareable Tests

on:
  push:
    paths:
      - 'shareable/**'
      - '.github/workflows/shareable.yml'
      - 'jest.share.config.json'
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
    branches:
      - master
    paths:
      - 'shareable/**'
      - '.github/workflows/shareable.yml'
      - 'jest.share.config.json'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out from the pull requested source
      uses: actions/checkout@v3
      if: ${{ github.event_name == 'pull_request' }}
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Checking out from the pushed source
      uses: actions/checkout@v3
      if: ${{ github.event_name == 'push' }}
      with:
        repository: ${{ github.event.push.repository.full_name }}
        ref: ${{ github.event.push.after }}
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}_${{ hashFiles('package.json') }}
          ${{ runner.os }}_
    - run: npm install
    - run: ./execute.ps1 -test unit:share
      shell: pwsh
      timeout-minutes: 3
